name 'cb_dvo_dynatraceagent'
maintainer ''
maintainer_email ''
license 'All Rights Reserved 2018, example Bicycle Corporation'
description 'Installs/Configures cb_dvo_dynatraceagent'
long_description 'Installs/Configures cb_dvo_dynatraceagent'
version '1.0.4'
issues_url 'https://bitbucket.org/example/cb_dvo_dynatraceagent/issues'
source_url 'https://bitbucket.org/example/cb_dvo_dynatraceagent'
chef_version '>=12'
supports 'centos'
