name 'cb_dvo_dynatraceagent'
maintainer 'Matthew Oleksowicz'
maintainer_email 'matt_oleksowicz@trekbikes.com'
license 'All Rights Reserved 2018, Trek Bicycle Corporation'
description 'Installs/Configures cb_dvo_dynatraceagent'
long_description 'Installs/Configures cb_dvo_dynatraceagent'
version '1.0.3'
issues_url 'https://bitbucket.org/trekbikes/cb_dvo_dynatraceagent/issues'
source_url 'https://bitbucket.org/trekbikes/cb_dvo_dynatraceagent'
chef_version '>=12'
supports 'centos'
